### ISSUE TITLE
bulk invoice issue

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/payments#171]
there might be a bug with the bulk invoicing feature.

"The bulk invoice actually only went through to the first person on the list – the subsequent recipients were in the ‘draft’ status and had to be sent individually."

"It now appears to be working, but after I press send to the group of folks we’re invoicing, the screen just gets stuck and doesn’t give any ‘sent’ or ‘done’ or other message. It is just stuck in ‘sending’ mode. I realized from the confirmation emails any by checking with the person I sent the other invoice to that the invoices are actually sending, it just doesn’t appear that they are when you’re using the system."

**Comment by jSylvestre** [comment]
Fixed
