### ISSUE TITLE
Report request

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/payments#210]
https://ucdavisit.service-now.com/nav_to.do?uri=incident.do?sys_id=INC0882451

Supplied Message Body:
Hello!

It would be very helpful to be able to get a report on the total income generated from each quarter's invoices. Right now in the 'Statistics' category, there is something that says ' $4,365 generated in the past 6 months.' I'm not sure where that comes from. Is it the total from the Flower Project + the Market Garden invoices?

I guess being able to sort by academic quarter or a date range, and an income account would be helpful for us to be able to accurately record income (without going in and adding it up by hand.) Would this be possible?

**Comment by srkirkland** [comment]
dup of #264
