### ISSUE TITLE
Non completed payments investigation

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/payments#220]
Many payments were completed and are in cybersource but are not in Sloth.  33 at the moment.  For example, it seems all payments made on 9/26/2019 were not grabbed by sloth.  

ex: https://payments.ucdavis.edu/student-farm-csa/Invoices/Details/253, https://payments.ucdavis.edu/bftv-cluster/Invoices/Details/357

If I go to cybersource and create the reports, I can download manually the report for the 27th which has many of those transactions, none of which are in sloth.

Why is a mystery, but here's metadata for the report that we need to somehow process

        OrganizationID="ucd_payments" 
        ReportStartDate="2019-09-27T07:00:00Z" 
        ReportEndDate="2019-09-28T07:00:00Z">

**Comment by jSylvestre** [comment]
Fixed in sloth
https://github.com/ucdavis/Sloth/pull/98
