### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/payments#240]
Delete attachment in the invoice edit page doesn't seem to do anything

**Comment by jSylvestre** [comment]
Don't delete from the storage account as the attachment may be used on multiple invoices

**Comment by sprucely** [comment]
I can't reproduce the problem. Since the delete attachment icon is identical to the delete line item icon, I suspect that a line item was mistaken for an attachment, because I did find a bug with deleting the last line item, #257

**Comment by srkirkland** [comment]
@sprucely not sure if you remember this far back, but from your comment it sounds like this is issue should be closed

**Comment by jSylvestre** [comment]
I do remember some work was done on this. I *think* it can be closed
