### ISSUE TITLE
Fix up LGTM issues if they look valid

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/payments#247]
https://lgtm.com/projects/g/ucdavis/payments/

**Comment by sprucely** [comment]
@srkirkland, for the hard-coded credentials, my initial thought was to replace them with values pulled in from IOptions<Settings>. Do you think appsettings.json is an appropriate place for email addresses and kerberos ids, or should that be considered user secrets?

Is it acceptable to alter repo history in order to completely eliminate sensitive data? If so, do you have a preference over the git filter-branch route vs BFG Repo-Cleaner?

**Comment by srkirkland** [comment]
In general, yes I think IOptions is the way to go.  While it is acceptable to alter repo history in case of truly sensitive data like a password, this data is really just public info so no reason to change the history.  However have a quick chat with @jSylvestre because my real feeling is that this code was just really for initial testing and now we can delete most/all of the hard-coded admin stuff.  Maybe we can leave up to one with the values being pulled from the appsettings file, if we really want to.

**Comment by jSylvestre** [comment]
@sprucely If this is code to create super users, you could change it like I did for PEAKS:
https://github.com/ucdavis/Peaks/blob/master/Keas.Mvc/Helpers/DbInitializer.cs#L34

Then that info is just in the user secrets

**Comment by sprucely** [comment]
@jSylvestre Thanks, I think I'll go that route. But I don't understand your last comment about it being in user secrets, as the code shows _superuserSettings coming from IOptions.

**Comment by srkirkland** [comment]
@sprucely IOptions the way comes from appsettings.json, appsettings.[env].json, and secrets.json, and more depending on the environment.  See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#default-configuration.

**Comment by jSylvestre** [comment]
As Scott said...
If you are using Visual Studio, you can get to the user secrets this way:

![image](https://user-images.githubusercontent.com/469010/76118699-bee15300-5fa2-11ea-805b-a25b82ea81c9.png)

**Comment by sprucely** [comment]
Ah, I should have known. In prior job I had created a configuration provider for pulling settings from a REST service. It makes sense that the user secrets integrates in a similar way. Thanks.
